In [1]:
# LISTAS
lista1 = [1, 2, 3] # O Python só identifica como uma lista através dos colchetes.

In [2]:
type(lista1)

list

In [3]:
lista2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
type(lista2)

list

In [5]:
lista1[0] # Para identificar um elemento (primeiro) da lista 1.

1

In [6]:
lista1[2]

3

In [7]:
lista2[0]

[1, 2, 3]

In [8]:
lista2[2]

[7, 8, 9]

In [9]:
lista2[0][2] # Seleciona o terceiro elemento da primeira lista.

3

In [11]:
lista2[2][2]

9

In [12]:
select = lista2[1][2]

In [13]:
print(select)

6


In [14]:
type(select)

int

In [18]:
select = lista2[2]

In [19]:
print(select)
type(select)

[7, 8, 9]


list

In [27]:
import random
cidades = ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Natal"]
escolhida = random.choice(cidades)
print("A cidade escolhida é:", escolhida)

A cidade escolhida é: São Paulo


In [28]:
a = [1, 2, 3]

In [29]:
a.append(15) # Comando para adicionar um novo elemento à lista.

In [30]:
print(a)

[1, 2, 3, 15]


In [31]:
b = [7, 8, 9]

In [32]:
for item in b: # Para cada um dos elementos de b...
    a.append(item) # Inclui cada elemento de b dentro da lista a.

In [33]:
print(a)

[1, 2, 3, 15, 7, 8, 9]


In [34]:
# TRANFORMANDO LISTAS FLOAT EM INT
num = 8
type(num)

int

In [35]:
float(num) # Converte a variável num de inteiro para float.

8.0

In [36]:
num1 = 3.5
type(num1)

float

In [37]:
int(num1) # Converte a variável num1 de float para inteiro.

3

In [38]:
x = [2, 4, 10, 6]
type(x)

list

In [41]:
print(x)

[2, 4, 10, 6]


In [44]:
nova = []
for item in x: 
    nova.append(float(item))

In [45]:
print(nova)

[2.0, 4.0, 10.0, 6.0]


In [1]:
# TUPLAS

### Ao contrário das listas, as tuplas são colocadas em parênteses.
### As tuplas são listas que não podem ser alteradas.

lista = [3, 6, 4]
lista[0] = 20 # Na lista é possível substituir os valores.
print(lista)

[20, 6, 4]


In [2]:
del lista[2] # Deleta o item dois da lista.
print(lista)

[20, 6]


In [3]:
tupla = (5, 3, 8)
tupla[0] = 30
print(tupla) # Retorna uma mensagem de erro informando que o intem não pode ser atribuído.

TypeError: 'tuple' object does not support item assignment

In [4]:
del tupla[2]
print(tupla) # Retorna mensagem de erro que não é permitido deletar item.

TypeError: 'tuple' object doesn't support item deletion

In [5]:
tupla.append(10)
print(tupla) # Retorna mensagem de que não é permitido adicionar valores à tupla.

AttributeError: 'tuple' object has no attribute 'append'

In [7]:
nova_tupla = tuple(lista) # Transforma a lista em tupla.
print(nova_tupla)

(20, 6)


In [8]:
type(nova_tupla)

tuple

In [9]:
numero = (3)
print(numero)
type(numero) # Informa que é um inteiro, pois para ser considerado tupla
## deve estar em forma de lista com vígulas entre os itens.

3


int

In [10]:
# DICIONÁRIOS

### Dicionários são apresentados com notação de chaves.
### Exemplo: dicionario = {chave:valor}.

dicionario = {'Curso' : 'Python para Machine Learning',
             'Produtor' : 'Didática Tech',
             'Preço' : 'Gratuito',
             'Nota' : 10} # Também podem ser atruídos valores.
dicionario['Preço']

'Gratuito'

In [12]:
dicionario['Nota']

10

In [13]:
a = dicionario['Produtor'] # Nova variável a recebe o atributo 'Pordutor' do dicionário.
print(a)

Didática Tech


In [14]:
dicionario['Preço'] = 'R$ 100,00'
dicionario['Preço']

'R$ 100,00'

In [15]:
print(dicionario)

{'Curso': 'Python para Machine Learning', 'Produtor': 'Didática Tech', 'Preço': 'R$ 100,00', 'Nota': 10}


In [17]:
dicionario['Pré-requisito'] = 'Python básico' # Para adicionar uma nova chave.
print(dicionario)

{'Curso': 'Python para Machine Learning', 'Produtor': 'Didática Tech', 'Preço': 'R$ 100,00', 'Nota': 10, 'Pré-requisito': 'Python básico'}


In [18]:
dicionario.keys()

dict_keys(['Curso', 'Produtor', 'Preço', 'Nota', 'Pré-requisito'])

In [19]:
dicionario.values() # Puxa os valores do dicionário

dict_values(['Python para Machine Learning', 'Didática Tech', 'R$ 100,00', 10, 'Python básico'])

In [23]:
dicionario.items() # Puxa todas as informações do dicionário.

dict_items([('Curso', 'Python para Machine Learning'), ('Produtor', 'Didática Tech'), ('Preço', 'R$ 100,00'), ('Nota', 10), ('Pré-requisito', 'Python básico')])

In [24]:
dicionario.clear() # Apaga todas as informações do dicionário.

In [25]:
print(dicionario)

{}


In [29]:
# MANIPULANDO STRINGS

frase = 'Estou gostando do curso.'
frase[2:6]

'tou '

In [30]:
frase[2]

't'

In [31]:
frase[9:12]

'tan'

In [33]:
frase[19:24]

'urso.'

In [34]:
frase[0:] # Imprime do primeiro caracter até o último.

'Estou gostando do curso.'

In [35]:
frase[2:13:2] # Puxa da posição 2 até a 13 pulando de 2 em 2.

'tugsad'

In [37]:
frase.count('t') # Conta a quantidade de letras 't'.

2

In [39]:
frase.count(' ') # Conta os espaços.

3

In [40]:
len(frase) # Conta o número de caracteres.

24

In [41]:
frase.replace('s', 'x')

'Extou goxtando do curxo.'

In [42]:
frase.replace('curso', 'aprendizado')

'Estou gostando do aprendizado.'

In [1]:
# FUNÇÃO LAMBDA

### Relembrando os conceitos da criação de funções.

def somaQuadrados(a, b): # Define o nome da função e os parâmetros utilizados.
    somaQ = a**2 + b**2 # Informa a fórmula da função.
    return somaQ # Pede o resultado da função.

In [2]:
somaQuadrados(4, 7)

65

In [3]:
### A função lambda cria novas funções, mas de forma resumida.

somaQuadrados2 = lambda a, b: a**2 + b**2

In [4]:
somaQuadrados2(5, 2)

29

In [5]:
calculadoraQuadrado = lambda a: a**2

In [6]:
calculadoraQuadrado(4)

16

In [7]:
x = lambda f: f/2

In [8]:
x(9)

4.5

In [36]:
# FUNÇÃO MAP

### Da mesma forma do lambda, o map resume o código.

kmh = [40, 50, 56, 64,  73, 79, 85, 96, 100, 120] # Lista de velocidades kilometros por hora.

mph = [] # Criando lista vazia.
for i in kmh: # Para cada item da lista kph...
    mph.append(i/1.61) # Adicione os valores na lista vazia divididos por 1.61.
print(mph)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [37]:
myRoundedList = [round(i,2) for i in mph] 

In [28]:
print(myRoundedList)

[24.84, 31.06, 34.78, 39.75, 45.34, 49.07, 52.8, 59.63, 62.11, 74.53]


In [40]:
mph2 = list(map(lambda x : x/1.61, kmh)) # Deve ser transformado em uma lista quando usa a função map().
print(mph2)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [41]:
myRoundedList2 = [round(i,2) for i in mph2] 
print(myRoundedList2)

[24.84, 31.06, 34.78, 39.75, 45.34, 49.07, 52.8, 59.63, 62.11, 74.53]


In [42]:
# LIST COMPREHENSION

### Permite criar funções ainda mais reduzidas.

mph3 = [x/1.61 for x in kmh]
print(mph3)

[24.844720496894407, 31.05590062111801, 34.78260869565217, 39.75155279503105, 45.3416149068323, 49.06832298136646, 52.795031055900616, 59.62732919254658, 62.11180124223602, 74.53416149068323]


In [43]:
myRoundedList3 = [round(i,2) for i in mph3] 
print(myRoundedList3)

[24.84, 31.06, 34.78, 39.75, 45.34, 49.07, 52.8, 59.63, 62.11, 74.53]


In [44]:
caracteres = [i for i in "Didática Tech"] # Puxa o caractere i para todos os elementos na string "Didática Tech".
print(caracteres)

['D', 'i', 'd', 'á', 't', 'i', 'c', 'a', ' ', 'T', 'e', 'c', 'h']


In [1]:
# Pacote Numpy

import numpy
a = numpy.array([1, 2, 3]) # Array de uma dimensão.
print(a)

[1 2 3]


In [4]:
import numpy as np # Importa o pacote como np para facilitar na escrita dos códigos
b = np.array([1, 4, 7, 3, 8, 34])
print(b)

[ 1  4  7  3  8 34]


In [5]:
c = np.array([(2, 7, 3), (65, 2, 89)]) # Matriz de 6 elementos.
print(c)

[[ 2  7  3]
 [65  2 89]]


In [6]:
d = np.array([(2, 7, 3), (9, 2, 6), (5, 3, 2)])
print(d)

[[2 7 3]
 [9 2 6]
 [5 3 2]]


In [7]:
e = np.zeros((4, 3)) # Cria uma matriz de zeros com dimensão de 4 linhas e 3 colunas
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
f = np.ones((4, 3)) # .array, .zeros e .ones são funções do pacote numpy.
print(f)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
g = np.eye(5) # Cria matriz com 5 linhas e 5 colunas com números 1 na diagonal.
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
d.max() # Informa o maior número da matriz b criada.

9

In [11]:
d.min()

2

In [12]:
d.sum() # Soma todos os elementos da matriz.

39

In [13]:
d.mean() # Média dos elementos da matriz.

4.333333333333333

In [14]:
d.std() # Calcula o desvio padrão.

2.4037008503093262

In [2]:
# COMO ABRIR ARQUIVOS USANDO O PANDAS

import pandas as pd

dados = pd.read_excel('C:/Users/jeann/Documents/Python/planilha.xlsx')

In [3]:
dados.head() # Apresenta apenas as primeiras 5 linhas.

numeros letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e

In [4]:
dados.head(7) # Apresenta as 7 linhas.

numeros letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f

In [10]:
# Acessar conjunto de dados do Kagle

### Conjunto de dados: 120 years of Olympic history: athletes and results

dados2 = pd.read_csv('athlete_events.csv') # Abre arquivo em formato csv

In [11]:
dados2.head(10)

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   
5   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   
6   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands   
7   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands   
8   5  Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands   
9   5  Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season         City          Sport  \
0  CHN  1992 Summer  1992  Summer    Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer       London           Judo   
2  DEN  1920 Summer  1920  Summer    Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer        Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter      Calgary  Speed Skating   
5  NED  1988 Winter  1988  Winter      Calgary  Speed Skating   
6  NED  1992 Winter  1992  Winter  Albertville  Speed Skating   
7  NED  1992 Winter  1992  Winter  Albertville  Speed Skating   
8  NED  1994 Winter  1994  Winter  Lillehammer  Speed Skating   
9  NED  1994 Winter  1994  Winter  Lillehammer  Speed Skating   

                                Event Medal  
0         Basketball Men's Basketball   NaN  
1        Judo Men's Extra-Lightweight   NaN  
2             Football Men's Football   NaN  
3         Tug-Of-War Men's Tug-Of-War  Gold  
4    Speed Skating Women's 500 metres   NaN  
5  Speed Skating Women's 1,000 metres   NaN  
6    Speed Skating Women's 500 metres   NaN  
7  Speed Skating Women's 1,000 metres   NaN  
8    Speed Skating Women's 500 metres   NaN  
9  Speed Skating Women's 1,000 metres   NaN

In [14]:
# INTRODUÇÃO AO PANDAS

import pandas as pd

alunos = {'Nome': ['Ricardo', 'Pedro', 'Angela', 'Cassia'],
         'Nota': [4, 7, 5.5, 9],
         'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

In [15]:
### Transformar o dicionário em um data frame

dataframe = pd.DataFrame(alunos)

In [16]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2   Angela   5.5      Não
3   Cassia   9.0      Sim


In [17]:
objeto1 = pd.Series([1, 6, 9, 10, 5])
print(objeto1)

0     1
1     6
2     9
3    10
4     5
dtype: int64


In [19]:
import numpy as np
array = np.array([1, 6, 9, 10, 5])
print(array)

[ 1  6  9 10  5]


In [21]:
array2 = np.array([(1, 6, 9, 10, 5), (7, 4, 9, 20, 8)])
print(array2)

[[ 1  6  9 10  5]
 [ 7  4  9 20  8]]


In [22]:
# Transformar array em um vetor

objeto2 = pd.Series(array) # Muitos dos comandos usados em dataframes também servem para séries.
print(objeto2)

0     1
1     6
2     9
3    10
4     5
dtype: int32


In [23]:
# COMANDOS ÚTEIS DO PANDAS

import pandas as pd

alunos = {'Nome': ['Ricardo', 'Pedro', 'Angela', 'Cassia'],
         'Nota': [4, 7, 5.5, 9],
         'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2   Angela   5.5      Não
3   Cassia   9.0      Sim


In [24]:
dataframe.head()

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2   Angela   5.5      Não
3   Cassia   9.0      Sim

In [25]:
dataframe.shape # Mostra quantas linhas e colunas o data frame apresenta.

(4, 3)

In [26]:
dataframe.describe() # Descreve a média, valores máximos e mínimos, desvio padrão, etc.

Nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000